# Generated by Django 3.2.9 on 2021-11-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
